name: Deploy Psicokawsay Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy backend folder
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVERPI }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "backend/**"
        target: "/var/www/html/backend"
        strip_components: 1
        overwrite: true

    - name: Run Laravel commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVERPI }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /var/www/html/backend
          composer install --no-interaction --prefer-dist
          php artisan migrate --force
          php artisan optimize:clear
          systemctl reload httpd
