name: Deploy Psicokawsay Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy via SSH using Git Pull
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVERPI }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          git config --global --add safe.directory /var/www/html/backend
          cd /var/www/html/backend
          git pull origin main
          composer install --no-interaction --prefer-dist
          php artisan migrate --force
          php artisan optimize:clear
          systemctl reload httpd
