name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVERPI }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./"
          target: "/var/www/html"

      - name: Run commands on server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVERPI }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo chmod -R 755 /var/www/html
            sudo chown -R apache:apache /var/www/html || true

